// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhynzjb3FuuE-VKQxXXlXsjVTKH4ikRUc',
    appId: '1:136720140564:android:484c464c9fc5cedd319a01',
    messagingSenderId: '136720140564',
    projectId: 'corvit-321d6',
    databaseURL: 'https://corvit-321d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-321d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV4E7undr-x9dKeUyuMgIaXbDffkbKlA8',
    appId: '1:136720140564:ios:dd904e74040264b8319a01',
    messagingSenderId: '136720140564',
    projectId: 'corvit-321d6',
    databaseURL: 'https://corvit-321d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-321d6.appspot.com',
    iosClientId: '136720140564-ns5p31n0j11h9vsmvd60d7ogtbpidlgo.apps.googleusercontent.com',
    iosBundleId: 'com.adnan.app.corvitapp',
  );
}
